### ATENCION GETALL
GET http://localhost:8080/atencion/fin-all

### ATENCION GETALLMIAS
GET http://localhost:8080/api/atenciones/mias
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1czEiLCJpYXQiOjE3ODY2NjI1NjEsImV4cCI6MTc4NjY2MzE2MX0.E7morL5fBoW1fm_bVc0nPD0Za3kZMEItoljawoz3wR4

### ATENCION GETBYID
GET http://localhost:8080/atencion/find/1

### ATENCION SAVE
POST http://localhost:8080/atencion/save
Content-Type: application/json

{
    "fecha" : "2027-01-12",
    "motivo" : "motivo2",
    "paciente_id" : null,
    "empleado_id" : 1
}

### ATENCION PUT
PUT http://localhost:8080/atencion/update/2
Content-Type: application/json

{
    "fecha" : "2026-01-13",
    "motivo" : "motivo22",
    "paciente_id" : 1,
    "empleado_id" : 3
}

### ATENCION DELETE
DELETE http://localhost:8080/atencion/delete/2