### PERSONA FINDALLTRUE
GET http://localhost:8080/api/personas?page=0&size=10&estado=true
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1czMiLCJpYXQiOjE3ODY5OTg2MjQsImV4cCI6MTc4Njk5OTIyNH0.VEw11ULtylF2oFWAdF8yVIymzCN_sYuxoBpUSAm-VKY


### PERSONA FINDBYID
GET http://localhost:8080/api/find/2

### PERSONA SAVE
POST http://localhost:8080/api/personas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1czMiLCJpYXQiOjE3ODY5OTY3MzMsImV4cCI6MTc4Njk5NzMzM30.Pay5nd7e510TV_-p0Qb8LinwIdWHkSHLDZldcj16YLE

{
    "nombre" : "lolo9",
    "email" : "lolo9@gmail.com"
}

### PERSONA PUT
PUT http://localhost:8080/api/update/2
Content-Type: application/json

{
    "nombre": "11johan",
    "email": "11email.com"
}

### PERSONA DELETE
DELETE http://localhost:8080/api/personas/9
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1czMiLCJpYXQiOjE3ODY5OTg2MjQsImV4cCI6MTc4Njk5OTIyNH0.VEw11ULtylF2oFWAdF8yVIymzCN_sYuxoBpUSAm-VKY




### USUARIO GETALL
GET http://localhost:8080/usuario/find-all

###USUARIO GETBYID
GET http://localhost:8080/usuario/find/1

### USUARIO SAVE
POST http://localhost:8080/usuario/save
Content-Type: application/json

{
    "usuario" : "us3",
    "contraseña" : "us3",
    "persona_id" : 5
}

### USUARIO PUT
PUT http://localhost:8080/usuario/update/6
Content-Type: application/json

{
    "usuario" : "usuario7",
    "contraseña" : "password7",
    "persona_id" : 2
}

### USUARIO DELETE
DELETE http://localhost:8080/usuario/delete/2
